local _, ns = ...

-- =========================================================================
-- Nagrand (Horde) - level 64-67
--
-- Rækkefølgen følger Wowheads leveling-guide for Burning Crusade Classic.
-- Quest-id'er og koordinater er verificeret mod pfQuest-databasen
-- (https://github.com/shagu/pfQuest, MIT-licens, © Eric Mauser/Shagu):
-- ACCEPT peger på quest-giveren, TURNIN på modtageren og DO på midten af
-- objective-området.
--
-- Koordinater er zone-procenter (x, y) på uiMapID:
--   1951 = Nagrand, 1949 = Blade's Edge Mountains
-- =========================================================================

ns.Q:RegisterRoute({
    key = "nagrand-horde",
    title = "Nagrand (Horde)",
    faction = "Horde",
    levels = "64-67",
    zones = { 1951 },
    next = "blades-edge-horde",
    steps = {
        -- ============================== Garadar ==============================
        { type = "TRAVEL", label = "Garadar",
          coords = { map = 1951, x = 55.4, y = 37.6 }, radius = 60,
          note = "Følg vejen fra Terokkar ind i Nagrand til Mag'har-byen Garadar (flight point)." },
        { type = "ACCEPT", quest = 9863, title = "Vile Idolatry",
          coords = { map = 1951, x = 54.8, y = 39.4 },
          note = "Fra Farseer Kurkush." },
        { type = "ACCEPT", quest = 9910, title = "Standards and Practices",
          coords = { map = 1951, x = 55.6, y = 37.5 },
          note = "Fra Elkay'gan the Mystic." },
        { type = "ACCEPT", quest = 9935, title = "Wanted: Giselda the Crone",
          coords = { map = 1951, x = 55.8, y = 38.0 },
          note = "Dusør fra Garadar Bulletin Board." },
        { type = "ACCEPT", quest = 9939, title = "Wanted: Zorbo the Advisor",
          coords = { map = 1951, x = 55.8, y = 38.0 },
          note = "Fra Garadar Bulletin Board." },
        { type = "DO", quest = 9863, title = "Vile Idolatry",
          coords = { map = 1951, x = 33.0, y = 41.0 },
          note = "Dræb Murkblood-Broken ved Sunspring Post (vest) og Laughing Skull." },
        { type = "DO", quest = 9910, title = "Standards and Practices",
          coords = { map = 1951, x = 56.0, y = 73.0 },
          note = "Dræb Kil'sorrow-orcs ved deres fæstning (sydøst)." },
        { type = "DO", quest = 9935, title = "Wanted: Giselda the Crone",
          coords = { map = 1951, x = 22.0, y = 28.0 },
          note = "Dræb Giselda the Crone på Warmaul Hill (nordvest)." },
        { type = "DO", quest = 9939, title = "Wanted: Zorbo the Advisor",
          coords = { map = 1951, x = 21.0, y = 30.0 },
          note = "Dræb Zorbo the Advisor på Warmaul Hill." },
        { type = "TURNIN", quest = 9863, title = "Vile Idolatry",
          coords = { map = 1951, x = 54.8, y = 39.4 },
          note = "Aflever hos Farseer Kurkush." },
        { type = "TURNIN", quest = 9910, title = "Standards and Practices",
          coords = { map = 1951, x = 55.6, y = 37.5 },
          note = "Aflever hos Elkay'gan the Mystic." },
        { type = "TURNIN", quest = 9935, title = "Wanted: Giselda the Crone",
          coords = { map = 1951, x = 55.8, y = 37.9 },
          note = "Aflever hos Warden Bullrok." },
        { type = "TURNIN", quest = 9939, title = "Wanted: Zorbo the Advisor",
          coords = { map = 1951, x = 55.8, y = 37.9 },
          note = "Aflever hos Warden Bullrok." },

        -- ======================= Throne of the Elements =======================
        { type = "ACCEPT", quest = 9870, title = "The Throne of the Elements",
          coords = { map = 1951, x = 55.4, y = 38.0 },
          note = "Fra Elementalist Yal'hah i Garadar." },
        { type = "TRAVEL", label = "Throne of the Elements",
          coords = { map = 1951, x = 60.7, y = 22.1 }, radius = 60,
          note = "Nordøst for Garadar: elementernes helligdom." },
        { type = "TURNIN", quest = 9870, title = "The Throne of the Elements",
          coords = { map = 1951, x = 60.7, y = 22.1 },
          note = "Aflever hos Elementalist Sharvak." },
        { type = "ACCEPT", quest = 9800, title = "A Rare Bean",
          coords = { map = 1951, x = 60.8, y = 22.4 },
          note = "Fra Elementalist Lo'ap." },
        { type = "ACCEPT", quest = 9818, title = "The Underneath",
          coords = { map = 1951, x = 60.7, y = 22.7 },
          note = "Fra Elementalist Untrag." },
        { type = "DO", quest = 9800, title = "A Rare Bean",
          coords = { map = 1951, x = 58.0, y = 30.0 },
          note = "Saml Bak'nari Coffee Beans på markerne." },
        { type = "DO", quest = 9818, title = "The Underneath",
          coords = { map = 1951, x = 61.0, y = 24.0 },
          note = "Undersøg The Underneath under thronet." },
        { type = "TURNIN", quest = 9800, title = "A Rare Bean",
          coords = { map = 1951, x = 60.8, y = 22.4 },
          note = "Aflever hos Elementalist Lo'ap." },
        { type = "TURNIN", quest = 9818, title = "The Underneath",
          coords = { map = 1951, x = 61.3, y = 24.8 },
          note = "Aflever hos Gordawg." },

        -- ========================= Nesingwary Safari =========================
        { type = "ACCEPT", quest = 10114, title = "The Nesingwary Safari",
          coords = { map = 1951, x = 55.4, y = 37.3 },
          note = "Fra Ohlorn Farstrider i Garadar." },
        { type = "TRAVEL", label = "Nesingwary Safari",
          coords = { map = 1951, x = 71.5, y = 40.8 }, radius = 60,
          note = "Hemet Nesingwarys jagtlejr i øst." },
        { type = "TURNIN", quest = 10114, title = "The Nesingwary Safari",
          coords = { map = 1951, x = 71.6, y = 40.5 },
          note = "Aflever hos Shado 'Fitz' Farstrider." },
        { type = "ACCEPT", quest = 9789, title = "Clefthoof Mastery",
          coords = { map = 1951, x = 71.5, y = 40.8 },
          note = "Clefthoof Mastery - fra Hemet Nesingwary." },
        { type = "ACCEPT", quest = 9854, title = "Windroc Mastery",
          coords = { map = 1951, x = 71.6, y = 40.5 },
          note = "Windroc Mastery - fra Shado Farstrider." },
        { type = "ACCEPT", quest = 9857, title = "Talbuk Mastery",
          coords = { map = 1951, x = 71.4, y = 40.6 },
          note = "Talbuk Mastery - fra Harold Lane." },
        { type = "DO", quest = 9789, title = "Clefthoof Mastery",
          coords = { map = 1951, x = 63.0, y = 50.0 },
          note = "Jag clefthoofs på sletterne (findes i hele Nagrand)." },
        { type = "DO", quest = 9854, title = "Windroc Mastery",
          coords = { map = 1951, x = 66.0, y = 45.0 },
          note = "Jag windrocs på sletterne." },
        { type = "DO", quest = 9857, title = "Talbuk Mastery",
          coords = { map = 1951, x = 60.0, y = 48.0 },
          note = "Jag talbuks på sletterne." },
        { type = "TURNIN", quest = 9789, title = "Clefthoof Mastery",
          coords = { map = 1951, x = 71.5, y = 40.8 },
          note = "Aflever hos Hemet Nesingwary." },
        { type = "TURNIN", quest = 9854, title = "Windroc Mastery",
          coords = { map = 1951, x = 71.6, y = 40.5 },
          note = "Aflever hos Shado 'Fitz' Farstrider." },
        { type = "TURNIN", quest = 9857, title = "Talbuk Mastery",
          coords = { map = 1951, x = 71.4, y = 40.6 },
          note = "Aflever hos Harold Lane." },
        { type = "NOTE", label = "Mastery-kæderne fortsætter", optional = true,
          coords = { map = 1951, x = 71.5, y = 40.8 },
          note = "Hver Mastery har tre trin (Clefthoof 9789->9850->9851, Windroc 9854->9855->9856, Talbuk 9857->9858->9859) og munder ud i 'The Ultimate Bloodsport'. Enorm XP - fortsæt sideløbende. Tryk 'Spring over', når du er klar." },

        -- ===================== Consortium: Aeris Landing =====================
        { type = "TRAVEL", label = "Aeris Landing",
          coords = { map = 1951, x = 31.4, y = 57.8 }, radius = 60,
          note = "Consortium-lejren ved foden af Oshu'gun i sydvest." },
        { type = "ACCEPT", quest = 9882, title = "Stealing from Thieves",
          coords = { map = 1951, x = 31.4, y = 57.8 },
          note = "Fra Gezhe." },
        { type = "ACCEPT", quest = 9914, title = "A Head Full of Ivory",
          coords = { map = 1951, x = 31.8, y = 56.8 },
          note = "Fra Shadrek." },
        { type = "DO", quest = 9882, title = "Stealing from Thieves",
          coords = { map = 1951, x = 35.0, y = 55.0 },
          note = "Saml Obsidian Warbeads/krystaller fra ogrer på Spirit Fields." },
        { type = "DO", quest = 9914, title = "A Head Full of Ivory",
          coords = { map = 1951, x = 40.0, y = 55.0 },
          note = "Saml elfenben fra clefthoofs." },
        { type = "TURNIN", quest = 9882, title = "Stealing from Thieves",
          coords = { map = 1951, x = 31.4, y = 57.8 },
          note = "Aflever hos Gezhe." },
        { type = "TURNIN", quest = 9914, title = "A Head Full of Ivory",
          coords = { map = 1951, x = 31.8, y = 56.8 },
          note = "Aflever hos Shadrek." },

        -- ==================== Mag'har-kæden og afslutning ====================
        { type = "NOTE", label = "Garrosh og Greatmother Geyah", optional = true,
          coords = { map = 1951, x = 55.4, y = 37.6 },
          note = "Lore-kæden fra Garrosh (via Kil'sorrow, Warmaul og elementerne) fører til 'A Visit With the Greatmother' og senere Thralls ankomst. Tryk 'Spring over', når du har fulgt den." },
        { type = "NOTE", label = "Ring of Blood (gruppe)", optional = true,
          coords = { map = 1951, x = 42.8, y = 20.7 },
          note = "The Ring of Blood ved Gurgthock: seks gladiator-kampe for en 5-mands gruppe - en af TBC's bedste XP-klumper plus et stærkt våben. Find en gruppe! Tryk 'Spring over', hvis du dropper den." },
        { type = "NOTE", label = "Ryd op i Nagrand", optional = true,
          coords = { map = 1951, x = 55.4, y = 37.6 },
          note = "Valgfrit: gør Mastery-kæderne og resterende Garadar-quests færdige indtil ca. level 66-67." },
        { type = "TRAVEL", label = "Mod Blade's Edge Mountains",
          coords = { map = 1949, x = 51.9, y = 58.4 }, radius = 100,
          note = "Flyv nordpå gennem bjergene til Thunderlord Stronghold i Blade's Edge Mountains. Qeasy skifter automatisk rute." },
    },
})
